### ISSUE TITLE
Manual transmission mod - gta has to be in focus?

### ISSUE THREAD

**Issue by freekanimal** [LukeRoss00/gta5-real-mod#319] opened 2021-02-14 04:02 UTC
Does the gtav window have to be in focus on order for my steering wheel to function? (So I can use SteamVRs VR View so others can view what I am in full screen) or is there a way to maximize the square gtav window?

**Comment by LukeRoss00** [comment] 2021-02-14 08:04
I'll close this as a duplicate of #314.

Anyway, you have three options:
1. Edit `settings.xml` and `commandline.txt` before running the game to set the window width to 1920 instead of 1080. This will cost you about 44% in performance due to the wasted pixels that GTA V will have to render that won't be visible in the headset. For instance, this means dropping from 90 fps to about 50 fps. Not advisable.
2. Connect a second monitor or a TV to your PC and put the SteamVR VR View there. Best solution.
3. Use a third-party utility like those shown at https://www.groovypost.com/howto/howto/windows-programs-always-on-top/ to make the SteamVR VR View stay always on top, then Alt-Tab back to the game, which will then be in focus but under the VR View window. Untested.

**Closed by LukeRoss00** 2021-02-14 08:04 UTC
