### ISSUE TITLE
Vive cosmos elite severe judder when moving head

### ISSUE THREAD

**Issue by virtualmisterl** [LukeRoss00/gta5-real-mod#202] opened 2020-06-10 21:42 UTC
Hi

I have a wireless cosmos elite & am experiencing severe judder when I move my head.
Fps vr, is reporting that its going from between 75 - 90 fps but dropping to 45 fps.
The judder is constant no matter the fps.
It seems possible  that motion smoothing is likely causing this but I have it disabled in my settings.
I'm wondering if it is somehow being forced on.
I even tried lowering settings but I get the same judder in low quality.

I also use valve index & with the same settings it runs beautifully on that, so as the resolutions are similar this seems to be cosmos specific.

As I'm using this with a yawvr motion simulator I really want the wireless cosmos to work so I can spin in endless circles.

I've already previously played through a large amount of the game with your mod without issue in the index.

Any help on this issue would be much appreciated.

My system spec:
I7 8700k @ 5.0ghz
2080ti oc 
32gb 3466mhz
All water cooled & stable

**Comment by virtualmisterl** [comment] 2020-06-10 22:43
Thanks for the quick reply.
Ok I just tried monoscopic mode.
The murder is there still but different.

In the normal mode, i found a road where I was holding 90fps.
Looked straight up the road & turned my head from side to side & as it judders everything separates ie.. the white line in the middle of the road becomes 2 lines etc..

In monoscopic mode it doesn't separate but it still judders just as badly

**Comment by LukeRoss00** [comment] 2020-06-11 09:08
Oh. That's pretty bad. That most likely means that the Cosmos software is not implementing the OpenVR spec correctly, i.e., probably in an effort to reduce latency it's disregarding the eye poses that I submit and using the last poses returned by WaitGetPoses() instead. For most games they're the same, but not for GTA V due to the way the multithreaded engine works.

Are there any user-configurable options in the Cosmos software, apart from the usual SteamVR generic settings? Anything that might persuade it to disable this "helpful" behavior?

**Comment by virtualmisterl** [comment] 2020-06-11 09:24
I did notice some settings in the vive console app which may have been related to that.
I think one I suspected was marked as motion compensation & spoke of reducing latency.
but they were already greyed out & not checked as default.
I wont be able to check again until later tonight but I will try to play with more settings & may be even test with a cable to see if it's a new feature/problem specific to the vive wireless adapter/cosmos combo.

**Comment by LukeRoss00** [comment] 2020-06-15 08:09
Were you able to make any progress?

**Comment by virtualmisterl** [comment] 2020-06-15 21:49
Sorry I haven't had time to get back on the game yet.
I should have a couple hours spare tomorrow night so I'll try to have a play with all the settings then

**Comment by virtualmisterl** [comment] 2020-06-17 20:21
I've been messing about with the cosmos tonight & no progress.
I've been through all the settings in the vive console app & steam vr settings.
The one promising setting which I mentioned before was off as default & turning it on makes no difference.
Also I've tried the headset wired.
Same problem.
I guess this is something the vive software is forcing.
Annoyingly with the cosmos, steam vr cannot run without vive console app.

So this problem probably isn't something you can do anything about.
If anything changes after future updates, i will report back but I may decide to sell the headset

**Comment by LukeRoss00** [comment] 2020-06-17 22:55
Ah, that's too bad.

I wonder why this happens so often: great hardware with reasonable price and amazing potential, ruined by sloppy software/driver execution. Logitech was that way for many years: hardware that went miles beyond any competition you could find at comparable or even higher prices, and drivers that completely sucked, with bugs reported by all users that went unfixed for years, to the point that customers would just buy a new hardware iteration in the hope that it came with a new version of the software.

Microsoft with its neglected WMR line is in the same boat today. Amazing headsets, and terrible software that seems to break with each Windows update. Bugs that never get fixed, and a general feeling of "I've just bought the wrong headset that nobody loves, not even its mother".

Valve on the contrary has wonderful software support, and horrible hardware problems that would be excusable if it were a startup with <10 engineers with no product experience, not the empire that Steam built.

Who knows, maybe a company that will be called the Apple of VR will finally come out and blow all hesitant competition out of the water, like Steve Jobs' Apple did with the iPhone. Or VR will just drown in an ocean of mediocrity and wavering, like 3D movies. It's really hard to tell at this point.

**Comment by virtualmisterl** [comment] 2020-06-18 00:09
Yeah I'm a bit disappointed in the cosmos elite.
Maybe they thought they were doing something clever with the software, without thinking of what else it could effect.

To be honest the hardware of it isn't too great either.
The strap design is a step back from the vive pro, the lens have the same god rays of all vive, they cocked up the new tracking meaning the new controllers aren't useable with the cosmos elite.
It feels a bit lazy & overpriced when you put it next to other new headsets.
Imo its only saviour right now is wireless.

I've never used oculus as I went with base station tracked from the start but I see the quest is ticking a lot of boxes now.

I do love the index as it's a great headset in so many ways.
But I bought day 1 & rma'd my controllers.
& tonight a base station 2.0 with probably less than 200 hours use just died & I valve have just confirmed it needs replacement.

I guess we're still awaiting something that ticks all the boxes.
I think vr is pretty safe now though. It's passed the main hurdles & anyone who tries it on a good headset sees that now.

Honestly it's a shame about 3d movies.
I owned a 2016 lg65c6 oled & that was possibly the pinnacle of 3d.
Passive comfortable glasses & perfect clean/clear popping 3d with beautiful colours & blacks.
Just as support was being dropped lol.
But then again you wouldn't want to watch everything in 3d all the time, so I understand it.

**Comment by LukeRoss00** [comment] 2020-06-18 08:28
I agree that VR as a technology is mature enough for mass adoption. Any sufficiently determined company could put together the best elements from the various solutions and, as you say, just put out a headset that ticks all the boxes.

However, I believe that it still can die from content starvation and pollution. It's been the same for 3D movies: the tech was basically perfect, at least in theaters (many home solutions had too much ghosting and too little separation to give a realistic effect). Yet most studios refused to do the right thing, which was to shoot with real 3D cameras like James Cameron had showed in Avatar with astounding success, and hallucinated instead that the business-sensible way to do things was to shoot in 2D to save a few bucks and just add a half-assed conversion in post-production.

That convinced most people that 3D is "only a gimmick" and that it gives you headaches, or it's just not worth the extra price. Big studios are doing the same thing with VR right now, and Valve cannot carry the torch alone.

**Comment by ThisIsntTheWay** [comment] 2020-06-18 11:46
For what it's worth, I got a cosmos elite as well - albeit without the wireless accessory.

If I got some time today/tomorrow, I'll try to reproduce the issue you had.
(Haven't tried out the mod yet.)

**Comment by virtualmisterl** [comment] 2020-06-18 17:53
That would be great if you could.
It's always good to get a second confirmation.

**Comment by ThisIsntTheWay** [comment] 2020-06-18 20:29
Alright, I was able to test it out with my cosmos:

Sadly, I too had experienced these jitters.
I even tried all the configs @virtualmisterl did, but nothing worked rectified the issue.

Disappointing, but sadly it seems that with the current software/driver of the Elite, this mod simply doesn't work properly.

**Comment by virtualmisterl** [comment] 2020-06-18 21:14
Ah that's a shame.
Thanks for trying.
Another blow for the cosmos

**Comment by LukeRoss00** [comment] 2020-06-20 08:57
Sorry guys ¯\_(ツ)_/¯

I'm closing the issue since apparently there is no solution ATM.

**Comment by LukeRoss00** [comment] 2020-06-20 11:45
Not Cosmos-related, but ironically it looks like the Apple of VR will be... Apple: https://www.bloomberg.com/news/articles/2020-06-19/apple-team-working-on-vr-and-ar-headset-and-ar-glasses

**Comment by LukeRoss00** [comment] 2020-07-02 21:47
On WMR headsets, it appears that the tracking problems get at least partially resolved if you press `B` once the mod keys are activated (#209). Would you guys care to try it with the Cosmos to see whether it makes any difference?

**Comment by virtualmisterl** [comment] 2020-07-04 18:01
Thanks for letting me know.
I still have the cosmos at the moment so I'll see if I get time to try it tonight

**Comment by LukeRoss00** [comment] 2020-07-05 11:04
I'm reopening the issue for ease of access, and also because I just released a new version that implements an experimental OpenXR rendering path.

I have no idea whether the Cosmos will work better or worse (or at all) using the OpenXR runtime, but it's worth a shot!

**Comment by LukeRoss00** [comment] 2020-07-16 10:50
Did you guys have a chance to try the new release of the mod with the Cosmos using the OpenXR runtime?

**Comment by northwind79** [comment] 2020-07-20 22:11
I just downloaded the latest version of the mod (release 5) and ran it with my HTC Cosmos.  There was a ton of flicker in release 4, that's gone, but I can report that there is quite a bit of jitter when turning my head in R5, I also lose audio despite the headset being the default.  I'll poke around with that some more.

System spec is:
Intel i9 @ 3.6GHz
32GB Ram
NVIDIA GeForce RTX 2080 Super
HTC Cosmos headset (non-elite).

**Comment by LukeRoss00** [comment] 2020-07-21 07:53
@northwind79 Did you set `VRAPI = 3` to enable the OpenXR backend?

**Comment by northwind79** [comment] 2020-07-21 14:53
I tried setting that in the realvr.ini, but when I did the game didn't start in the headset.  I'm going through SteamVR if that helps.  When I switched it back to 0 and retried, the game started as expected, still with the jitter / double vision when turning my head.  Upside, the audio magically worked. :)

**Comment by LukeRoss00** [comment] 2020-07-21 17:29
Audio is a separate issue, which can easily be fixed either by having the GTA V game window as the foreground (focus) window, or by setting `Mute Audio On Focus Loss` to `Off` in the Audio options page.

In order to enable the new OpenXR backend that I introduced in Release 5, it's mandatory that you specify `VRAPI = 3` in the .ini file: if you leave it to `VRAPI = 0` you'll be using the old OpenVR rendering path, so it's expected that the image will still be jittering. If the game doesn't show in the headset when you put `VRAPI = 3`, it's possible that you're not using the latest SteamVR version (I believe that their OpenXR implementation is available only in the beta branch of SteamVR).

**Comment by northwind79** [comment] 2020-07-21 17:57
I just updated to SteamVR Beta 1.14.1.  The game now loads with VRAPI = 3, however the load screen appears in a window over the default background, and when story mode starts I only see the mini-map on the lower left.  If I pause the game, I get all the standard menu options (still in the window).  On the desktop the game displays.  I'm also running the "High" settings.  My current OpenXR runtime is set to SteamVR.  The Desktop Game Theater option is also unchecked.  Let me know if there are any debug logs I can flip on to help.  Thanks!

**Comment by LukeRoss00** [comment] 2020-07-21 18:03
Yes, you can enable the mod's own log by adding a line `RVRLog = 1` to the `RealVR.ini` file. Play for a minute or two, then after quitting the game you will have a new `RVRLog.txt` file in the game folder. Please zip and attach it here, let's see if it tells us anything interesting :-)

**Comment by northwind79** [comment] 2020-07-21 19:31
Zipped log is 40mb, 10mb limit here.  Here's a link to it: [RVRLog.zip](http://www.tothemetal.net/wp-content/uploads/2020/07/RVRLog.zip)

**Comment by LukeRoss00** [comment] 2020-07-21 22:28
Thanks! I've examined the log. Unfortunately it looks like Valve's implementation of OpenXR is not mature enough for the moment :-(

Specifically, a couple of bugs that were already reported [here](https://steamcommunity.com/app/250820/discussions/8/2647504242049377020/) and [here](https://steamcommunity.com/app/250820/discussions/8/2647504242046572684/) are preventing the mod from running correctly and from displaying the game world in VR.

**Closed** 2020-07-24 12:20 UTC

**Comment by virtualmisterl** [comment] 2020-08-19 23:15
Hi. a little late but i finally got around to getting the cosmos back out again.
I guess you already know but just to confirm, pressing b does nothing.
Also setting vrapi = 3 I get the same result as Northwind79.
Game boots in a window then when it loads, i only see the minimap.
Game seems to be disconnected from the vr headset.
