### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by rikiwelche** [LukeRoss00/gta5-real-mod#383] opened 2021-07-26 18:44 UTC
hello luke
Since the last game update and scriptthook, my game crashes when loading story mode.
I have always done all the updates without problem so I wonder if it would not be related to your vr mode that should be updated as well.
thank you to you ... and especially for your great job!

**Comment by LukeRoss00** [comment] 2021-07-26 18:59
Duplicate of #382

**Closed by LukeRoss00** 2021-07-26 18:59 UTC
