### ISSUE TITLE
WMR stutter fix

### ISSUE THREAD

**Issue by coru182** [LukeRoss00/gta5-real-mod#209] opened 2020-06-25 05:20 UTC
Hey, sorry to create a post on this but wanted to share my findings. Turns out if I press “B” on my keyboard the stutters go away. I can do it on demand. If I press “b” I basically enable/disable the stutter. Also, whenever I press that I hear a sound in game as if something was activated, but could not find any references in the mod documentation about what “b” does.

Tested on Samsung odyssey plus

**Comment by LukeRoss00** [comment] 2020-06-25 08:32
`B` is an internal toggle that changes how far ahead the camera angles are corrected by the mod.

I saw from your post on Reddit that you play in monoscopic mode (so unfortunately 'B' is not a panacea for the WMR woes). Does 'B' have any effect for you if you toggle it while in stereo 3D mode? Do you notice any difference in the tracking glitches?

**Comment by coru182** [comment] 2020-06-25 12:24
Yes. Same thing when In stereo 3D. Pressing B makes stutters disappear and the only thing left is the “ghosting” for AER. Overall it makes a much better experience. That’s why I was excited to share!!

**Comment by LukeRoss00** [comment] 2020-06-25 12:46
It's amazing that it works for you, but I cannot see how. As you saw from the Reddit thread, Microsoft themselves state that they don't support the different poses needed for alternate eye rendering.

**Comment by coru182** [comment] 2020-06-25 14:04
I thought the bug was going to fix the "ghosting" that happens when enabling 3D. Anyway, i can reproduce this consistently so i'm just happy to be able to fix that stuttering even in mono mode (as my brain makes it 3d for some reason :D)

I tested in a clean Win10 install. Using WMR for SteamVR BETA and SteamVR Beta.

PC Specs: 8700k + 2080RTX + Odyssey+  (Also tested with the AcerHMD and it works the same)

I'm curious to see if this fixes stuttering for other WMR users as well or if at least others are getting a better experience as well. 
BTW, I found the hotkey while trying to turn on FPS with the headset on and mistakenly pressing "B" instead of "N". LOL.

**Comment by coru182** [comment] 2020-06-25 15:56
i'm going to try to capture a video to show you the results. Will upload to youtube whenever i get a chance. 
Since the main issue i was having is fixed, i'm going to be enjoying the mod a lot now. 
If you want me to test anything or gather any logs please let me know. 

Would love for others using WMR to enjoy your mod as much as I'm doing now!!

**Comment by coru182** [comment] 2020-06-25 21:26
@LukeRoss00 This might be complete bullshit, but i edited the RealVR.ini file and added this to the INI:

; U           Select pitch control (always, only when aiming, never) - always at start
PitchControl = 0

Which seems to allow me to freely aim with the mouse. 

[RealVR.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4833884/RealVR.txt) <-- Here's my RealVR.ini file in case anyone is interested. Just need to change the extension from .txt to .ini

I call it the perfect config for WMR. (if you don't mind playing in monoscopic mode and want to aim using the mouse. Lol)

Using that config file, once in game the only thing i need to do is press "/" to center view and then "B" to get rid of stutters and i'm golden.

**Comment by coru182** [comment] 2020-06-25 21:35
In case anyone is interested, here's my RealVR.ini file. With this config i'm able to independently look with the headset and aim with the mouse at the same time.  Keep in mind the config sets rendering to monoscopic mode, so its not 3d. 

[RealVR.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4833919/RealVR.txt)

Currently playing with 1200 res and 2/5 rendering its glorious 
With that config, the only thing i need to do is launch the game and once in-game i just press "/" to center view and then "b" to get rid of stutters and i'm golden!

Thanks so much for creating this Mod man!!!! This is amazing!!

**Comment by LukeRoss00** [comment] 2020-06-26 09:31
You're welcome :-D

You can make the `B` behavior the default by adding a line `FixTrackedFrameIndex = 0` to your `RealVR.ini` file.

The stuttering is caused by wrong reprojection, so it's normal that it can't be seen in the game window. You could try capturing the SteamVR headset mirror window. Unfortunately nothing interesting will appear in any logs because the issue is deep within the Microsoft driver, not in any code accessible to the mod.

**Comment by coru182** [comment] 2020-06-26 18:35
OMG, you are a genius. Now i can just boot the game and start playing without any other fixes.!!

Do you know if there's a way to detach arms from head view while driving and aiming?? With my RealVR.ini settings I can aim and move my head independently when walking, but when I aim while driving, the camera gets fixed to the heaset position. I can aim with the mouse, but would like to aim with the mouse and independently move my head around, like when walking. Is that possible? Thanks!!

**Comment by LukeRoss00** [comment] 2020-06-26 23:42
The hotkeys you're using are the relevant ones. I don't believe that what you're trying to achieve while driving and aiming is possible though, because the gameplay camera behaves differently when you're in a vehicle and is a lot more constrained. However, you've already managed to extract some very unexpected behavior out of the mod with your tweaks, so I wouldn't rule it out altogether!

**Comment by OneToo** [comment] 2020-06-30 06:09
FixTrackedFrameIndex = 0
This stabilized the game for the Quest a lot.  Not perfect, but playable.  Just in time, can't get link to work.

**Comment by LukeRoss00** [comment] 2020-07-07 14:26
I forgot to ask you: with Release 5 of the mod and OpenXR, do you find that `B` makes any difference anymore?

**Comment by coru182** [comment] 2020-07-07 14:28
Haven’t tried it cause it has been working perfectly, so really didn’t need
it. I’ll test it today after work and let you know.

**Comment by coru182** [comment] 2020-07-08 20:17
Hey man, sorry for the delay.
I just tested it and could not see any difference whatsoever when pressing
B in both 3D and 2D mode.
However, i'm not really sure what i'm looking for exactly. Looking around
it all looked the same with no discernible changes.

is there anything in particular i should be focusing on?

**Comment by LukeRoss00** [comment] 2020-07-08 20:28
If it had any effect, it would be visibile in the tracking quality and stability, just like you discovered with the WMR driver for SteamVR.

Your being unable to see any difference now matches my experience with the Oculus runtime (that's why I left the `B` key undocumented originally: because it would be confusing to have an option that has no apparent effect). It's good news actually: it means that the mod behaves on WMR like I designed it to do initially on Oculus.

I'll close the issue at this point, thanks again!

**Closed by LukeRoss00** 2020-07-08 20:28 UTC
