### ISSUE TITLE
Stuttering/ Poor performance

### ISSUE THREAD

**Issue by monk3e** [LukeRoss00/gta5-real-mod#199] opened 2020-06-06 16:25 UTC
Hi mate. I've installed the mod following your guide. The game launches as it should via oculus. But i cant for the life of me get a smooth framerate. 

I have tried the Low Medium and High default settings. But it plays as if its running at about 5fps.

My system is 6 core xeon at 4.2ghz, 24gb ram, RTX 2070 and usually have zero issues with AAA titles. Game is installed to a Nvme drive, and i am using an oculus rift CV1. Any advice would be greatly appreciated.

**Comment by LukeRoss00** [comment] 2020-06-06 16:31
It should be running smooth on your config. What does the batch file report when you choose the settings? Any errors?

**Comment by LukeRoss00** [comment] 2020-06-06 16:32
Also, what does the frame rate counter say? (`F11` and then `N`)

**Comment by monk3e** [comment] 2020-06-06 21:19
I'll check soon, the batch file runs well, no errors. my gpu useage is at 1-5% when in game though. seems odd. i was using a hmm cheeky torrent. I'm busy downloading the Epic version to see if it helps

**Comment by monk3e** [comment] 2020-06-07 18:56
Just thought i'd update the thread. It was the pirated version that caused the issue. (I own several copies,) i just had a huge fight with the Epic install 2 weeks ago before the new script hook was out, and i thought the copied version would be easier. WRONG! 

Its working brilliantly now. Huge respect for what you do, the mod is absolutely amazing! 

Keep up the good work dude!

**Comment by LukeRoss00** [comment] 2020-06-08 07:23
Awesome of you to write back! I'll close the issue now, but it will be helpful for other players to know that severe performance issues can be caused by "unofficial" game versions ;-)

**Closed by LukeRoss00** 2020-06-08 07:23 UTC
