### ISSUE TITLE
Release 5.0: OpenXR artifacting Vega 64

### ISSUE THREAD

**Issue by Chris9a** [LukeRoss00/gta5-real-mod#228] opened 2020-07-20 21:32 UTC
Radeon RX Vega 64 
AMD driver v20.7.2
Intel i7 4770
Samsung Odyssey+ WMR
Windows 10 v2004
GTA V rockstar launcher clean install no mods

![RX_Vega_64_7_20_2020_1](https://user-images.githubusercontent.com/68567233/87986272-e7c63880-caaa-11ea-9dbe-e3d3afb06056.png)
![RX_Vega_64_7_20_2020_2](https://user-images.githubusercontent.com/68567233/87986273-e85ecf00-caaa-11ea-90d7-452eaaf46a77.png)
![RX_Vega_64_7_20_2020_3](https://user-images.githubusercontent.com/68567233/87986276-e8f76580-caaa-11ea-856a-ef934fb554c5.png)
![RX_Vega_64_7_20_2020_4](https://user-images.githubusercontent.com/68567233/87986277-e8f76580-caaa-11ea-8e4c-67abacf37cfa.png)

**Comment by LukeRoss00** [comment] 2020-07-21 07:50
Another user reported the very same artifact on Reddit (https://www.reddit.com/r/WindowsMR/comments/hndp20/tips_to_getting_real_vr_mod_for_grand_theft_auto/fxb08wk) and he has an almost identical config, apart from your Intel i7 4770 vs his Ryzen 1700.

At this point I suspect a driver bug, possibly related specifically to the Vega 64, because I have no other reports of a similar problem, and I cannot reproduce it on my system. Did you also try SteamVR mode (`VRAPI = 0`) to check whether the issue only occurs with OpenXR?

**Comment by Chris9a** [comment] 2020-07-21 18:58
I tried VRAPI = 0. The game is opened through SteamVR and it does not display any artifacts. Something I noticed when using OpenXR is that the GTA V window does not display the artifacts. It is only visible in the headset. I also tested the OpenXR developer tools app and got errors when I launched the demo. I don't know if any of this helps.

Before launching demo:
![OpenXR_1](https://user-images.githubusercontent.com/68567233/88091631-55cb3800-cb5d-11ea-91e4-7e2a05c70b4a.png)

After launching demo:
![OpenXR_2](https://user-images.githubusercontent.com/68567233/88091652-5f54a000-cb5d-11ea-8860-8234986ccf95.png)

**Comment by LukeRoss00** [comment] 2020-07-21 19:14
The error from the demo just means that there was another program already using OpenXR (possibly GTA V had not exited correctly, or another instance of the demo?).

The facts that the mod does not show any artifacts on your system when you select SteamVR mode, and that other users with different video cards can run it successfully in OpenXR mode, really points to a driver or runtime bug. Sadly, I can already tell you that it's the kind of super-specific bug that developers never get around to fixing, but you _could_ try using the WMR feedback hub to at least report the problem to Microsoft and hope for a miracle...

**Comment by LukeRoss00** [comment] 2020-07-21 19:18
Another thing you could try yourself is experimenting with the antialiasing options in the game's graphics settings menu: perhaps there is some combination of FXAA and MSAA that works.

**Comment by LukeRoss00** [comment] 2020-07-24 12:19
@Chris9a Were you able to solve your problem? Do you have anything else to ask or should I close the issue?

**Comment by Chris9a** [comment] 2020-07-24 15:31
You can close it, I will submit the issue to the feedback hub.

**Comment by LukeRoss00** [comment] 2020-07-24 15:56
OK, feel free to reopen here if you have new information!

**Closed by LukeRoss00** 2020-07-24 15:56 UTC
