### ISSUE TITLE
GTA V update killed the mod...

### ISSUE THREAD

**Issue by kidron2579** [LukeRoss00/gta5-real-mod#317] opened 2021-02-12 02:47 UTC
I have been using your VR MOD for the last few weeks, and I have to tell you I really love it. The sad news is that I think the game auto updated or something and now I get a SCRIPT HOOK V CRITICAL ERROR and I can't play the gamer at all. Is there a fix for this?

**Comment by LukeRoss00** [comment] 2021-02-12 07:12
Thanks for the appreciation! I'm closing the issue as it's a duplicate of #315, you can either try to downgrade or just wait for a few days till Script Hook V gets updated to match the new game version!

**Closed by LukeRoss00** 2021-02-12 07:12 UTC
