### ISSUE TITLE
Gyro Stabilization?

### ISSUE THREAD

**Issue by Ribonizer** [LukeRoss00/gta5-real-mod#339] opened 2021-03-13 04:00 UTC
Hi,

I'm not quite sure this is an issue or something by design. Basically, if you happen to barrel your car, the car rolls around the view. My view is always fixed to the ground. I've pushed every button and trying with Gyro Stabilization 1 and 0 in my ini. So I dunno if it's by design. It makes flying a plane pretty much impossible and it's kinda annoying in vehicles.

Pushing O makes it the view remains fixed  but headtracking is completely gone.
I've hit End a bunch of times and it's not doing anything. I was able to get so both direction do it so the car even rolls around me when I'm driving not sure which button, to tell you the truth pushing keys on my keyboard with the HMD on isn't easy.

Everything else is absolutely perfect and this is an incredible mod.

I'm wondering I'm doing something wrong.

I'm using a Samsung Oddysey+ Windows Mixed Reality, but I'm running the game through the Steam version so my API is autodetect but I think it's using Steam VR. Everything else works great running that way.

Game version's 1.0.2215.0 but this was happening before this version dropped.
Using Release 7

I have 0 crashes do you really need my whole computer's specs? Performance is fine!
[RealVR.log](https://github.com/LukeRoss00/gta5-real-mod/files/6134137/RealVR.log)

**Comment by LukeRoss00** [comment] 2021-03-13 08:31
The behavior you're describing (vehicle rolling around you while your view remains horizontal) is not the default; however, it was asked for by several users, so I introduced the `GyroVehicle` option to activate it. The default is to have `GyroVehicle = 0`, which disables the behavior and makes your view roll around with the vehicle you're in. As you described, with `GyroVehicle = 1`, planes are almost impossible to fly and the effect is very unnatural.

I don't know why the End key has no effect for you, but setting `GyroVehicle = 0` in the .ini file _before_ running the game should fix your problem.

On a different note, with WMR you will have much better tracking by taking SteamVR out of the equation and using OpenXR. See the [release notes](https://github.com/LukeRoss00/gta5-real-mod/releases): basically you need `VRAPI = 3` in the .ini file and your WMR OpenXR runtime installed and active.

**Comment by Ribonizer** [comment] 2021-03-13 15:59
Oh wow, yeah switching the API to OpenXR improved the headtracking tremendously as well as performance, I'm getting better FPS and the jitter when head tracking is completely gone...

Gyro sync is still on, but I've just realized that it's only on when I'm not aiming. If I aim while driving, gyro kicks off, in fact, the END key works while aiming and I can see it turning on and off. But as soon as let go of the aim it will revert to forced gyro stabilize. But I also notice a weird desaturation of color when I aim. I'll try to troubleshoot this some more tonight after work.

I'm only running two mods and I can't imagine they would interfere with this; Manual Transmission, and a Trainer mod, not sure which I don't even remember installing a trainer but as I was mashing the keyboard I did bring up a training menu *shrugs*

This is most puzzling.

**Comment by LukeRoss00** [comment] 2021-03-13 16:25
Oh, you should have mentioned the Manual Transmission mod. It has a custom camera that gives problems with VR, look into its menus for an option to switch it off.

**Comment by Ribonizer** [comment] 2021-03-13 16:36
Huzzah!

There we go, that was the culprit. It also fixed that really annoying thing when you braked at high speed it would make your camera fly into the dash. I thought that was working as intended since your character actually leans forward when you break because he doesn't put his seatbelt on.

Thanks for assistance, good thing you knew about that mod's issue because I don't think it ever would have occurred to me that a mod meant to make my racing wheel work was also messing around with the camera.

**Comment by E66666666** [comment] 2021-03-15 09:57
> a mod meant to make my racing wheel work was also messing around with the camera

It's enabled by default because the synchronized first person animations break the first person camera yaw - and the custom camera is there to basically replace/fix that.

There used to be a check to disable it with RealVR but people complained they actually preferred that camera so I made it optional, there's an option in the debug -> compatibility section to completely disable the first person camera logic.

I'm open for suggestions, though:

* Disabling custom first person camera by default will result in me getting spammed with "I can't look left/right!" comments
* Disabling improved steering animations by default is just ugly and too immersion-breaking

**Comment by LukeRoss00** [comment] 2021-03-15 10:07
When VR is active (i.e., at all times when `RealVR.asi` is loaded) I already tweak the camera so that looking left/right with complete freedom should always be possible. I'm not sure about the improved steering animations: @E66666666, do they depend on your custom camera?

**Comment by E66666666** [comment] 2021-03-15 10:12
I don't own a VR headset so I can't check the behavior - users requested it so I just made sure it's optional.

With the improved steering animations the game somehow locks the camera yaw, so with normal gamepad/keyboard-mouse gameplay it's pretty much a necessary option.

**Comment by LukeRoss00** [comment] 2021-03-15 10:15
> With the improved steering animations the game somehow locks the camera yaw, so with normal gamepad/keyboard-mouse gameplay it's pretty much a necessary option.

When VR is active I force the camera yaw to the input coming from the VR headset, so that should not be a problem. I also can't check personally though, because I don't own a steering wheel! Can your mod be used with a normal Xbox gamepad or does it need a steering wheel to be present?

**Comment by E66666666** [comment] 2021-03-15 10:34
Yeah, it's also fully functional with a gamepad and/or keyboard.

**Comment by LukeRoss00** [comment] 2021-03-15 10:40
Okay, I'll give it a spin then and let you know what I find

**Comment by LukeRoss00** [comment] 2021-03-15 13:22
So, I tried Manual Transmission (MT) together with R.E.A.L. VR (RVR) using an Xbox controller. I can confirm what @Ribonizer [wrote](https://github.com/LukeRoss00/gta5-real-mod/issues/339#issue-830798366): when the custom camera is active, all vehicles (planes included) roll around you while your view stays aligned with the horizon, making normal driving weird and flying planes very hard and unnatural. This is not MT's fault: it's just the interaction with how RVR needs to treat scripted cameras.

If I understand correctly, MT implements the improved steering animations by using 3rd person animations, and those are only available when seeing the world through a 3rd person camera. Thus, despite the name, MT's custom FPV cam is actually a scripted 3rd person cam, and that causes the weird behavior when interacting with RVR.

So, unless I'm wrong and there actually is a way to make the 3rd person steering animations work with a true 1st person cam, I can't figure out a simple solution.

On the other hand, I was unable to reproduce the issues reported by other users. With MT and RVR active, and with all possible states of the custom FPV cam (disabled, enabled, attached to player's head or vehicle or default 1st person cam) looking left and right was always completely free and unrestricted, and I couldn't see any warping or distortion of the image.

**Comment by E66666666** [comment] 2021-03-15 13:38
> and those are only available when seeing the world through a 3rd person camera

These also work with the real first person camera. The first person camera just gets limited to about 15 degrees of yaw either side, while I'm actively playing the third person animations.

> custom FPV cam is actually a scripted 3rd person cam

Basically, yes. 

> So, unless I'm wrong and there actually is a way to make the 3rd person steering animations work with a true 1st person cam, I can't figure out a simple solution.

Well I could try and adjust the first person camera matrix like you do, but that'd just result in another conflict.

On my side, I could make the custom camera opt-in instead of opt-out ([relevant menu setting](https://github.com/E66666666/GTAVManualTransmission/commit/ceeb5ea6ef24bce86eb04453c688a117ceb8ccdb#diff-12bec9feb447c75b74330cb90959f757b88f00197e0b60b709877811ab355b73R2192)) but I'd rather not. I could also add an API function where the option can be toggled by another program/script, or you could directly change the option in my settings file (though that requires a reload of my script to detect). Lastly I could also restore the RealVR.asi detection *and* change the "Disable globally" override to "Enable even with RealVR present" but that'd just feel like a very tacky workaround.

**Comment by LukeRoss00** [comment] 2021-03-15 13:49
> These also work with the real first person camera. The first person camera just gets limited to about 15 degrees of yaw either side, while I'm actively playing the third person animations.

However, in my testing disabling the custom FPV cam also seemed to disable the improved steering animations. I'm not 100% sure because I have no real steering wheel to check with, but testing with the controller stick, when the custom FPV cam was disabled the character's hand would only rotate a bit without ever crossing, while when the custom FPV cam was enabled I was able to see the hand-over-hand animation that I guess corresponds to the improved version.

**Comment by LukeRoss00** [comment] 2021-03-15 13:58
> I could try and adjust the first person camera matrix [...] make the custom camera opt-in instead of opt-out [...] add an API function [...] directly change the option in my settings file [...] "Enable even with RealVR present"

All of those options are possible, and I thank you for suggesting them, but as you say they are just workarounds and each of them incurs the risk of confusing users even more.

The only clean solution that I can see at the moment is keeping the true 1st person gameplay cam together with the 3rd person animations (only when `RealVR.asi` is detected, to avoid the yaw limitations), but as I wrote in my previous comment I'm not sure whether it can be made to work.

**Comment by E66666666** [comment] 2021-03-15 15:05
> in my testing disabling the custom FPV cam also seemed to disable the improved steering animations

Oh christ why'd I make this so configurable...

There are several systems at play here, all can be individually toggled.

1. Customized steering wheel bone rotation
    1. Current input is Steering Wheel (*implicitly* enabled)
    2. Custom Steering (keyboard/gamepad steering override feature)
        1. `ES: Override wheel rotation` option checked
2. Third person steering wheel animations (for synchronized >90 degrees steering animations)
    1. `Misc options` -> `Sync steering animation` checked
    2. Only enabled if either the current input is steering wheel or custom steering is active
3. Custom Camera (To fix the camera restrictions imposed by `2.`)

So, only the Custom Camera thing conflicts with your mod, but apparently `Custom Steering` isn't enabled by default. I'll need to revise my defaults, and probably turn off the custom camera - and somehow find a way to inform users that they should turn it on...

**Comment by LukeRoss00** [comment] 2021-03-15 15:56
> Oh christ why'd I make this so configurable...

😄

> apparently Custom Steering isn't enabled by default

I don't know: I just checked, and for me the `ES: Override wheel rotation` option was already checked. Despite that, toggling `Misc options` -> `Sync steering animation` seems to have no visible effect.

What I see is this (remember that I'm using an Xbox controller and have no real steering wheel, so my observations might not apply to the expected use case). When I push the controller stick all the way to one side, the in-game steering wheel of the car turns a maximum of about 60°. That never changes, no matter what I tweak. The character's hands remain rigidly attached to the car's steering wheel (and so turn about 60°) only when the custom FPV camera is disabled; otherwise if I enable the custom FPV camera, no matter what else I try to change, the character performs the hand-over-hand steering animation and thus appears to want to steer about a full turn, although the car's steering wheel still rotates a max of 60° (so the hands appear to slide over the wheel).

**Comment by LukeRoss00** [comment] 2021-03-27 08:04
@E66666666 Do you have anything to add on the matter or should I close the issue?

**Comment by E66666666** [comment] 2021-03-27 08:41
Not really. I'll figure out how to make things more obvious in the settings and defaults, in the meantime you can just tell users to disable the default-enabled custom camera thing.

**Comment by LukeRoss00** [comment] 2021-03-27 09:11
Will do, thanks!

**Closed by LukeRoss00** 2021-03-27 09:11 UTC
