### ISSUE TITLE
wrong FOV in 2d mode?

### ISSUE THREAD

**Issue by chotus** [LukeRoss00/gta5-real-mod#100] opened 2020-02-09 11:59 UTC
hi again LukeRoss

just a quick question.. I kinda get over the ghosting at times with the 3d rendering method and would be happy to go to the 2d mode, but when i do the FOV seems off conpared to the 3d FOV is this normal? and if so is there something i can change to fix it?

thanks for your time

**Comment by LukeRoss00** [comment] 2020-02-09 12:10
Duplicate of #98

**Closed by LukeRoss00** 2020-02-09 12:10 UTC
