### ISSUE TITLE
Mission glitches & Bugs

### ISSUE THREAD

**Issue by cercata** [LukeRoss00/gta5-real-mod#27] opened 2019-11-07 23:03 UTC
After beating the game 100%, some feedback

- Mission Father/son: When following the boad on the highway, there was some kind of weird auto-recenter, making it very very hard aiming
- Nervous Ron: When trevor is over the wing of the Cuban 800, auto-recentering again, making it very very hard
- Freefall: If you fail to shut down the plane with the mega-snipper, you come to a control point, and this second time is different, you don't have the camera locked, and you can't aim, I had to restart the mission.
- Multi-target assassination: After starting the mission, there is a weird effect, like it's not VR anymore, it's kind of a 3D screen that moves a little with you. The minimap is broken, and aiming with guns was also broken, so I couldn't beat the mission on VR, I had to play flat.

Beside that, the drift was my main issue, a little inmersion breaking.

Thanks so much for making a dream come true, GTA VR !!!
I was specting someone to make a mod for San Andreas, I didn't expect GTA 5 until at least 2021 !!!
Now I'll start experimenting with MODs.

**Comment by LukeRoss00** [comment] 2019-11-08 09:59
> Mission Father/son: When following the boad on the highway, there was some kind of weird auto-recenter, making it very very hard aiming
Nervous Ron: When trevor is over the wing of the Cuban 800, auto-recentering again, making it very very hard

I don't remember that in Father/Son, but yes, some specific missions put your character in a sort of autopilot mode where the camera controls become super stiff. I haven't figured out a solution yet.

> Freefall: If you fail to shut down the plane with the mega-snipper, you come to a control point, and this second time is different, you don't have the camera locked, and you can't aim, I had to restart the mission.

I assume you mean Caida Libre? I never tested failing that mission, usually I'm able to bring the plane down without problems. But again yes, there are a few missions where failing the objective puts the game in a super-weird state that I have no idea how to test for and/or to remedy. For instance in Chop, if you fail a specific checkpoint you completely lose left/right headlook and you actually need to quit out of the game to recover, restarting the mission isn't enough.

> Multi-target assassination: After starting the mission, there is a weird effect, like it's not VR anymore, it's kind of a 3D screen that moves a little with you. The minimap is broken, and aiming with guns was also broken, so I couldn't beat the mission on VR, I had to play flat.

I never had trouble with The Multi Target Assassination, and I think I never saw the effect you describe. Did you try restarting the game? It might have been a temporary glitch.

> Beside that, the drift was my main issue, a little inmersion breaking.

The "drift"? What do you mean by that?

> Thanks so much for making a dream come true, GTA VR !!!
I was specting someone to make a mod for San Andreas, I didn't expect GTA 5 until at least 2021 !!!
Now I'll start experimenting with MODs.

Good!! Let us know if you find any mods that work beautifully with this one! [This post](https://redd.it/drve6p) might give some good pointers to get started!

**Comment by cercata** [comment] 2019-11-08 10:29
> I assume you mean Caida Libre?
Yes, I have the game in Spanish, and I was translating the mission names, didn't know that one was originally on Spanish xD


> I never had trouble with The Multi Target Assassination, and I think I never saw the effect you describe. Did you try restarting the game? It might have been a temporary glitch.
I'had that effect like 4-5 times over 80h gameplay, but in other cases it wen't out just by reloading.
But in the multitarget assassination, even restarting the game didn't work.

I wonder if haviong the game saved beside the Car Wash could have an effect.

Anyway, if I'm the only one to report it, it doesn't matter.


> The "drift"? What do you mean by that?
I mean having to recenter too often, sometimes because an event change direction a lot, other times I don't know if it has been gradual, or a discrete small change that I notice later.

**Comment by LukeRoss00** [comment] 2019-11-08 11:03
Do you play seated or standing? With KB/M or a controller?

**Comment by cercata** [comment] 2019-11-09 17:35
Seated with a Xbox ONE controller !!!!

**Comment by LukeRoss00** [comment] 2019-11-09 22:14
So, same as me. Odd that you should have a tracking drift, there is nothing in the mod that could cause that. Although perhaps we're not meaning the same thing... Do you experience something like the HUD slowly changing angle, or position, with respect to same fixed reference in the real world (like your desk or a wall)?

**Comment by cercata** [comment] 2019-11-11 07:29
When I play relaxed, searching for drift, I see nothing.
And when action starts, I have to recenter a lot ot times. I guess it's a recentering, that sometimes lets me 45º off, and other times 5º offf, and I think it's drift.

> there is a weird effect, like it's not VR anymore, it's kind of a 3D screen that moves a little with you. The minimap is broken, and aiming with guns was also broken, so I couldn't beat the mission on VR, I had to play flat.

I had this issue while playing LSPDFR quite consistenly. It starts when I'm close to the door of a 24/7, and after that it continues all the time. I have a trick now for getting rid of it, I enter the 24/7, i look to the exit, and I go looking forward until I'm 10m outside the 24/7

It seems like if you are turning your head while in some transition near busineses (Car Wash, shop, ...), it starts. I friend told he had the same issue.

**Comment by LukeRoss00** [comment] 2019-11-11 09:46
Does the "3D screen" effect occur when you're close to ATMs?

**Comment by cercata** [comment] 2019-11-11 18:30
> Does the "3D screen" effect occur when you're close to ATMs?

Yes, it's that !!!!
I can reproduce now the glitch in the Multi Targe Assassination miision.
There is an ATM in the gast station shop, if you get close to the ATM inside the shop, when you get away it 4m, the effect dissapears.
But if you get close to the ATM outside the shop, the effect doesn't dissapear, and that's what happened to me everytime in the mission, since I avoided the car wash xD

I made a video illustrating it:
https://youtu.be/xCv3Goam1Yc

**Comment by masher42** [comment] 2019-11-11 18:48
> there is a weird effect, like it's not VR anymore, it's kind of a 3D screen that moves a little with you

I've had this effect happen a lot and it was always outside of missions. So, it's not just you. It's really annoying when it happens. Fortunately it doesn't happen often. 

> But if you get close to the ATM outside the shop, the effect doesn't dissapear

Very interesting find. That's at least one of the triggers. I noticed right when it first happened it looks like the effect in front of the ATMs, but I couldn't reproduce it.

**Comment by LukeRoss00** [comment] 2019-12-17 14:38
All problems with ATMs should be fixed in the [new release](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r2). Feel free to reopen this issue if that is not the case for you

**Closed by LukeRoss00** 2019-12-17 14:38 UTC

**Comment by VadarVillage** [comment] 2019-12-25 07:34
On Caida Libre (Freefall) mission I found a "fix" for the issue that occurs after failing mission.  You have to press the key to exit the vehicle.  Your character wont actually exit the vehicle, but for some reason this resets the camera and you can then attempt to shoot down the plane again.

so, if you have to retry Caida Libre, try to exit the Van and it will enable you to aim with the gun again.
