### ISSUE TITLE
got game running.....but

### ISSUE THREAD

**Issue by modifiedbrock** [LukeRoss00/gta5-real-mod#167] opened 2020-04-28 08:11 UTC
Dont know if this is an isssue for anyone else but when i run vr all i get is a black screen in game, i have hud and sound just my pov is black.
So when i attempt to move or look around my mini map goes all weird as if im above or below the game.
The game is ok on monitor just not on my rift s any help would be great

**Comment by LukeRoss00** [comment] 2020-04-28 14:09
Possible duplicate of #162

**Comment by Aikimaniak** [comment] 2020-04-29 23:02
Hello Luke,
first of all let me thank you for your absolute piece of art. I have the time of my life playing GTA V this whole new way, it is just amazing!!!! 
I am playing it with Other mods on, so with a force feedback wheel a Hotas and a bike controller, just sick!!! 
Unfortunately I have a little issue maybe you can help me fix: 
When I play with my Pimax (Steam VR supported headset, not oculus) the reset the view option by shaking your head doesn’t work. This option is absolutely hassle free it is so natural when I switch from my wheel to my hotas with rudder positon to just shake my head and continue flawlessly the gameplay...
It works fantastic with the oculus but not on the Pimax.
I really enjoy the purity of the image of the Pimax and it is hard to trade the large FOV of the Pimax for the Oculus... 
Are you aware of this issue? Would it be hard to fix it? Can you tell me how I could do it or could you check that in your next update?
It would be lovely!!!

PS: I’ve managed to make your mod work with REDUX, it wasn’t easy but man!!!!!!! It is absolutely pure magic, the image is cristal clear and the depth of view is x10 time better, it was a pain in the S because I am new into the modding world but I found the file that makes your mod goes glitchy inside Redux and changed it... if you are interested you can message me privately...
Cheer from France
Daju

**Closed** 2020-05-02 07:55 UTC
