### ISSUE TITLE
Sometimes it works, sometimes it doesn't

### ISSUE THREAD

**Issue by Enschede2** [LukeRoss00/gta5-real-mod#134] opened 2020-03-17 22:38 UTC
It's absolutely awesome when it works, however when it doesn't it crashes right after the loading screen, the only thing that will work then would be to reconfigure the settings.xml file, which unfortunately I'd then have to finetune again.
It's almost as if when it crashes just once, the settings file gets corrupted or something because from that point on it will crash every single time until I replace the settings file again

**Comment by Jesusavesouls** [comment] 2020-03-18 00:39
Surprises me since its simple to install and load.Did you put the appropriate settings file in documents of rockstar/gta5...either low,med or high ? What headset and gpu do you have ? I have a gtx1080 and managed to only get 90 fps on med at 90 hz if I look out into the ocean with no scenery such as buildings.I would like to know if anyone is getting a constant 90fps or higher ? What does it do on a 2080ti ?

**Comment by KptnKMan** [comment] 2020-03-23 17:39
This issue is clearly nothing to do with FPS of anyone.

I've also seen an issue where the game will not start anymore with the mod, after starting without issues. After this, it wont start anymore and I've had to reinstall GTA5 twice, then reapply the mod on top per the docs.

For me, restoring the mods settings.xml still crashed the game when using the VR mod. I'm using the High" setting. If the mod was removed, then the game would start in without VR. However, installing the mod again would break everything until the game was reinstalled.

Its not the end of the world, but reinstalling a 90GB game is not fun, and I'm sure my ISP doesn't appreciate it. 🙁

**Comment by LukeRoss00** [comment] 2020-03-24 08:23
I never once needed to reinstall the game, even when developing the mod. My mod only _adds_ files in the main game folder, it doesn't replace or overwrite anything. Even the `settings.xml` file (which is not in the game folder and not involved in the uninstall/reinstall process) gets backed up before any changes.

The most likely cause for those game "corruptions" are mod managers or conflicts with other mods.

**Comment by KptnKMan** [comment] 2020-03-24 14:57
I appreciate you getting back to us about this.

I'm not using any mod managers, and have not used any other mods for GTA5 personally. This is otherwise a clean vanilla install from Steam.
Honestly, I'm not sure why it did this multiple times. I checked for memory corruption, and verified GTA5 files in steam multiple times. Removed all the mod files, Installed mod again from the verified download.

Its only after the complete reinstall did everything work again.

Is there anything you suggest to try if this happens again? Thanks.

**Comment by LukeRoss00** [comment] 2020-03-25 09:15
If you have data caps, the best insurance against this kind of incidents is copying the whole game folder to a backup folder. That way, if anything weird happens, you can always restore without downloading again (and you can also use folder comparison programs like WinDiff to discover exactly which files, if any, got corrupted).

**Comment by KptnKMan** [comment] 2020-03-29 18:14
I'd really appreciate if this issue was not closed.

I just went to play GTA 5 again, without changing anything since my last play, and the same has happened. No idea what is going on, I'm only greeted with this screen after a few seconds:
![image](https://user-images.githubusercontent.com/12234043/77856663-f1c0e480-71f8-11ea-81c5-1701f2069960.png)

This happens immediately after the Rockstar logo and before the in-game main menu launches. I could reinstall again, and install the mod over the top, but I'd really appreciate help with resolving this.

I'm not changing anything else but installing the mod before this happens. I've tried to reinstall the mod files and settings.xml, but the game still crashes the same way.

I'm going to backup the current files and try a clean install, and WinDiff, as advised.

**Comment by Jesusavesouls** [comment] 2020-03-29 19:25
This is not likely caused by the vr mod but mods.I had this happen and you
have to exit steamvr and steam client.If it doesn't work then restart the
pc.

**Comment by KptnKMan** [comment] 2020-03-29 19:33
I've definitely exited Steam VR and restarted my PC multiple times each time this has happened. I've spent a lot of time trying to get this to work before coming here. Something else is going on, and I'm **definitely not using any other mods**. It's a clean install otherwise.

Look man, I'm just saying, so far I can't see any other modification to this game that could possibly be the issue. I have never had this with any other game, and I have many games installed.

I only play GTA 5 for the excellent VR experience this mod provides, so I'm very grateful to the creator for this **free mod**... but something's up.

**Comment by Jesusavesouls** [comment] 2020-03-29 22:16
Try putting in the mods settings files into documents and overwrite.Try
another alternate too like med instead of high.What hmd you using ? Update
nvidia and the os.

**Comment by Jesusavesouls** [comment] 2020-03-29 22:29
Also if your also on the latest release and also place the files over the
other ones again.

**Comment by LukeRoss00** [comment] 2020-03-30 12:26
@KptnKMan Let us know what you find using WinDiff. Also, could try adding `-scOfflineOnly` to the `commandline.txt` file? So that you boot directly into story mode instead of going through the main menu.

**Comment by Jesusavesouls** [comment] 2020-03-30 12:44
Is there a way to place something or remove in the files to stop all future
gta updates ? Those updates always mess up the game for modders.

**Comment by KptnKMan** [comment] 2020-04-03 08:03
So I've finally found some time to get some testing done last night. Unfortunately, some other things started happening like the recent scriptV update, which broke everything for a while. have it working now, and encountered another strange issue in #145.

@LukeRoss00 I did a WinDiff between the backed-up folder and there seems to have been no difference between them apart from log files, so thats good news.

@Jesusavesouls I did reinstall the mod over the top, overwriting everything and ensuring settings were from presets.

I also added the `-scOfflineOnly` to the `commandline.txt` per LukeRoss00's advice. The game still has to launch via the Rockstar Launcher though, and will not run from any other executable, it just seems to skip the menu selection. Is there something better I can do there?

I spent time cleaning, removing and reinstalling everything on my system to do with VR, just to be sure that there were no driver, application or service issues. The game still didn't work and a reinstall of the game got it working again.

I've also downloaded a "Repacked" version of GTA5 to test in isolation from my Steam-purchased version. Also because it wont get auto-updated and may not break in that respect.

Still testing, but it seems to be working now. Will have to see if the config corruption happens again.

**Comment by Jesusavesouls** [comment] 2020-04-03 11:02
So not sure if scripthook was updated but don't really care.Instead I found
a downgraded launcher.This info is in the recent comments on gta5 mods and
in the mod there for scriothook.It had also a link for the downgraded
launcher and a bypasser.Too I used
-scofflineonle.Now it starts smooth without needing to update.One day it
would be nice if rockstar stops updating the game.So as of now I believe I
won't need to update anymore.If it's true then my game will be pretty much
less problem prone.Jesus loves you !

**Comment by LukeRoss00** [comment] 2020-04-13 09:31
I'm closing this again due to inactivity, feel free to reopen if needed

**Closed by LukeRoss00** 2020-04-13 09:31 UTC

**Comment by Jesusavesouls** [comment] 2020-04-13 12:17
Why close discussions that people are communicating in just because it's
not constant traffic ? Jesus loves you !
