### ISSUE TITLE
Staying in first person view after explosions or crashes ? 

### ISSUE THREAD

**Issue by Jesusavestill** [LukeRoss00/gta5-real-mod#302] opened 2021-01-14 14:55 UTC
I’ve tried trainers and mods. After I sink under water or a vehicle explodes while driving. It always goes to 3rd person view. It can’t manage to let me stay in fpv after the character dies or the driver dies when in vehicle. After the complete destruction of a vehicle your driving, it goes to third and out of first. Only using the www.grandtheftvr.com mod by Bo will it keep you in first person.

**Comment by LukeRoss00** [comment] 2021-01-14 18:18
I'm closing the issue because this behavior is by design. What you describe is exactly what the game camera always does, even when playing in 2D.

Other mods might circumvent this behavior (which again is coded in the game itself, not introduced with my mod) by replacing the normal gameplay camera with a scripted camera, but that's not something I do.

**Closed by LukeRoss00** 2021-01-14 18:18 UTC
