### ISSUE TITLE
Pimax large fov

### ISSUE THREAD

**Issue by Believe-ConfessJesus2Bsaved** [LukeRoss00/gta5-real-mod#311] opened 2021-02-06 13:42 UTC
Mod works terrific. Just wondering if there is a work around for the fov large @ 170 to correctly project ? I use so many custom resolutions that all work. I can use Pimax potatoe, small and normal but never the large fov.

**Comment by LukeRoss00** [comment] 2021-02-06 14:03
Duplicate of #304

**Closed by LukeRoss00** 2021-02-06 14:03 UTC
