### ISSUE TITLE
Scripthook exception

### ISSUE THREAD

**Issue by DeadPixels1** [LukeRoss00/gta5-real-mod#337] opened 2021-03-12 15:36 UTC
Hi having some issues trying to get this mod running. Some assistance would be appreciated.

Oculus Rift S
Epic game version 1.0.2215.0 same scripthook version
R.E.A.L. Mod Release 7
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No
 
Steps I took.
fresh install
copied the contents of GTAV_REAL_mod_by_LukeRoss_r7.rar to the games root dir (where the .exe file is)
copied latest scripthook.dll to same dir
Ran realconfig.bat on H, 2 files were copied and no errors were reported.

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6131076/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6131088/asiloader.log)

Seems to work but after the first cutscene the games HUD/menus are visible but not anything else, it displays correctly on the monitor in a window (as expected I think) but it's like it's not transmitting the whole picture to the headset.

**Comment by JimmY-PT** [comment] 2021-03-12 23:58
Yestarday I had this issue too...
I tried this mod before and worked flawlessly but this time, i don't know why, it happened exactly how @DeadPixels1 explained...
I changed all the settings before copying the files into the folder.....

Settings> Gamepad> Targeting Mode : Free Aim
Settings> Camera>  First Person Head Bobbing: Off
Settings> Camera>  First Person Third Person Cover: On
Settings> Camera>  First Person Vehicle Hood: Off

If anyone can help, it would be greatly appreciated

**Comment by LukeRoss00** [comment] 2021-03-13 08:43
This looks like a duplicate of #336. Please follow the instructions [here](https://github.com/LukeRoss00/gta5-real-mod/issues/336#issuecomment-796291886) to generate a full mod log that I can examine, and continue the discussion in #336. You can also try [this solution](https://github.com/LukeRoss00/gta5-real-mod/issues/335#issuecomment-795331350) that worked for another user.

**Comment by LukeRoss00** [comment] 2021-03-13 08:44
Duplicate of #336

**Closed by LukeRoss00** 2021-03-13 08:44 UTC
