### ISSUE TITLE
Having trouble with the batch file.

### ISSUE THREAD

**Issue by dliebermail** [LukeRoss00/gta5-real-mod#68] opened 2020-02-02 03:53 UTC
Hi! 

I'm here from Reddit. THANK YOU! 

Anyway, I have changed the location of my documents folder. It's now: 
D:\Documents\

With the batch file un-edited, I get this error when I try to run "medium"

Select High, Medium or Low config [H,M,L]?M
The system cannot find the path specified.
The system cannot find the path specified.
        0 file(s) copied.
        1 file(s) copied.
Press any key to continue . . .

So, per your instructions I replace the full path to my documents folder, like so: 
SET dst=D:\Documents\Rockstar Games\GTA V
(I checked and the settings.xml file is in there)
and I get this error

Select High, Medium or Low config [H,M,L]?M
The system cannot find the file specified.
        1 file(s) copied.
        1 file(s) copied.
Press any key to continue . . .

It seems like one more file is copied? I did try your previous version. I couldn't take the cut scenes, so I uninstalled everything. This is a fresh install. 

Any help you can provide will be greatly appreciated. I'm very excited to play!

**Comment by LukeRoss00** [comment] 2020-02-02 10:20
It seems that you did the operation correctly, and the batch file is now copying both files, so I don't understand what the problem is! Does the game crash, or...?

**Comment by dliebermail** [comment] 2020-02-03 04:03
Actually, it did work. Thank you!

**Comment by LukeRoss00** [comment] 2020-02-03 09:52
Great! I'm closing the issue then

**Closed by LukeRoss00** 2020-02-03 09:52 UTC
