### ISSUE TITLE
Slight, yet annoyingly noticeable, FPS deviation Oculus Rift S

### ISSUE THREAD

**Issue by VolkertJansz** [LukeRoss00/gta5-real-mod#109] opened 2020-02-13 22:30 UTC
First of all I want to say: The work you did on the R. E. A. L mod is absolutely freaking awesome... I'm 50 hours deep into GTA again and loving every drive, stroll, flight... you name it. Next to iRacing (and Superhot iis also cool I guess :p) the best VR experience out there! Especially combined with steering wheel and the car physics mod for some nice drifting trough Los Santos. Awesome job. I couldn't be more grateful!!!

A question though, I am running the game on a 2080TI and 8700k on the Rift S (I turn off the 3D with numpad2 because of the judder and somehow my mind turns it into 3D so that's great)

Your in-mod fps counter shows a very rapidly (as in per frame alternating 80/79 fps.) the game runs super smooth when this alternates. But when the fps is on 79 (or occasionally even 81-82) for more then 1 frame is see an annoying stutter (especially prominent when fast cornering). Now, through all this, the Oculus debug tool shows a very constant 80 fps line without any deviations at all.

Im quite sure the framerate deviation is not related to my hardware power because even on the lowest settings (I believe it's 600*600, right) you provide the counter says the same.

Do you have any clue what I could do to get it smoother? Why does Oculus debug say constant 80 when your counter says it isn't (and it obviously isn't indeed) Is there a way to at least cap the fps to 80 so that I have the stutter only on the 79 side of 80? (I'm going nuts to the point of considering buying an Index but they're sold out).

Thanks again for the work, it's a true gem!

**Comment by LukeRoss00** [comment] 2020-02-13 22:39
Happy to see that you're enjoying the mod and the game so much!!!

A few questions: how long does the stuttering last? Is it just a momentary glitch (a single missed frame), or does it last for like half a second or more? What happens if you don't use monoscopic mode? There should be no judder even in stereo mode, the only artifact should be laterally moving objects appearing to double. Did you make sure to turn ASW off (either from the OTT or with the Oculus hotkeys)?

**Comment by VolkertJansz** [comment] 2020-02-13 23:05
-The stuttering (or stutter, singular I should say) lasts for a couple of frames, so miliseconds but still noticable. I see it is correlates with your in-mod fps counter (which when the game runs "smooth" is continously alternating per frame between 80/79 fps) going to 79 for a couple of frames or occasionally when it goes to 81 or 82 fps. Meanwhile the Oculus debug tool performance overlay  give a 100% straight line @80 fps. This inconsistency isn't likely to be related to my GPU or CPU performance as it doesn't change when going to the L settings you provided.

- I only use the mod in monoscopic it is indeed not the AFR judder as I always have it turned of. 

- Yes I've tried with ASW disabled.

**Comment by VolkertJansz** [comment] 2020-02-13 23:07
Ah sorry, I misread your question. I will test it now with AFR mode.

**Comment by VolkertJansz** [comment] 2020-02-13 23:59
Ok, so I've done some more testing and I have to correct my earlier statement that the oculus debug overlay doesn't pick up the stutters. It does; it will show a very brief 77.5 and the "application frames dropped" counter will go up by 1 frame.

I again checked if it was also the case with the L settings and the problem was still there, so it is not hardware restrictions that cause it a assume.

It doesn't matter whether I use mono or alternate.

**Comment by LukeRoss00** [comment] 2020-02-14 10:56
Thanks for the additional information. How frequent are the stutters? Like, every couple of seconds, or are they a much rarer event? Apart from fast cornering, is there a way to reproduce them reliably, e.g. a particular place in the game map where they occur very often?

**Comment by VolkertJansz** [comment] 2020-02-14 12:30
It occurs every 5 seconds or so. I've been trying a bunch of things last night and this morning. Turning off hyperthreading, moving GTA from SSD to my HDD, ending every possible background process I can think of, pulling out my ethernet cable. Nothing seems to help. 

It is not location related, it happens everywhere on the map. Inside the car as well as out. Day, night. Moving/looking around and standing still. It's just with cornering I notice it the most.

It's driving me nuts! PC masterrace :D! Can't eat, can't sleep ;P 
Horror...lol

**Comment by LukeRoss00** [comment] 2020-02-14 12:55
OK, I just checked again and I cannot reproduce the issue on my system (1080 Ti, so your config should work even better). There is the _very_ occasional lost frame that increments the Application Frames Dropped when the game loads an animation/model/whatever for the first time, but nothing like every few seconds, and if I stand still or drive carefully without killing people and things there are no lost frames _at all_.

So I'm afraid it's something on your system, and I know very well that problems like this are extremely difficult to diagnose. Usual suspects are shovelware "utilities" like RGB lighting, overlays, antivirus apart from Windows Defender... but a single misbehaving driver anywhere in the system can also lead to issues like the one you describe.

**Comment by VolkertJansz** [comment] 2020-02-14 13:02
Yeah, tell me about it. I think I might be looking at a fresh windows install or something. 

One more suspiscious thing I've just noticed. When I'm playing iRacing I have steady 80 FPS without any drops but the Debug overlay says I only have 60% headroom. With GTA where Oculus says I have 99% headroom, I get the frame drops. That 99% seems strangely high to me. 

Anyway, Thanks for the kind help so far. I'll pick it up again over the weekend.
Your mod still rocks though!
Cheers

**Comment by LukeRoss00** [comment] 2020-02-14 13:23
The 99% headroom is probably meaningless, just a measurement error due to GTA V not being a native VR application. One last thing you could try is turning off the waiter thread in the mod by pressing `NUMPAD+` when the hotkeys are active. Usually that leads to poorer performance, but in your case it might be beneficial, who knows.

Also, if you're very knowledgeable, you might use a tool like [LatencyMon](https://www.resplendence.com/latencymon) to try and investigate your problem without reinstalling Windows.

**Comment by VolkertJansz** [comment] 2020-02-14 13:59
Thanks, I'll give those options a try!

**Comment by d0x360** [comment] 2020-02-17 01:38
I haven't used the mod yet so all these tips may not apply.

First I'd get a program called bills2 process manager and make a rule in it to set GTA5 to run at above normal priority (not high).  Also go into the options of bills2 and set it so it doesn't lower other processes to low automatically because you don't want it setting the Oculus runtimes to low


I'd also get Oculus Tray tool if you don't have it.  You can use this instead of bills2 to set the game to a above normal priority.  You can also disable certain Oculus features and control things like super sampling from the menu or even while in game with your voice.

I've found that shutting steam vr's automatic super sampling off and using Oculus tray tool improves performance and image quality but... This is the one I don't know about because I don't know if this mod enables steam vr or not.  That said using the tray tool has helped me smooth performance in a ton of games, significantly at times.

I'm gonna try this out tomorrow, I also have a rift s and a 2080ti but my CPU is older.  I have an i7 5820k (6 cores @ 4.6ghz), 32 gigs ddr4 and the game is running off a very fast pcie nvme ssd.

It's possible you are getting frame pacing issues as the game tries to fetch data but.. who knows.  That's kinda what it sounds like.

**Comment by VolkertJansz** [comment] 2020-02-17 07:31
Thanks a lot for these suggestions, haven't tried those yet indeed.

I did put GTA VR to the side for a little while because I want to maybe wait with putting the rest of the 100 hours in until I get an Index. This is such an amazing experience that I want to enjoy it in the best possible way. But please do let me know if you can get the game+mod running without any hikkups. I will definitely try your suggestions if I find myself in a game drought before I can get an Index.

Another thing I've noticed is that when I limit the framerate to 75 with Riva it still gives me those framedrops, just now with an fps decrease to 72.5 as opposed to 77.5. Another confirmation that it really isn't my hardware specs. Also running 32 gigs ddr4 btw.

Thanks for the input, curious about your findings, 
Cheers!

**Comment by Dipster78** [comment] 2020-02-19 09:45
Hi.
First off all thank you so much for this mod!
To personal to explain it in detail. But for me this mod is so awesome to be able to drive and walk around in a city. And it is GTA V....so big bonus!

I had the same isseu with stuttering every 5 seconds sinds I downloaded it.
But only one time it just was perfect without the stutters and I couldn't find the problem why it didn't work anymore.
Tried allot of things but none of them worked. To the point I wanted to delete it all. 

Then I turned on Task manager and I saw that the game used my intergrated graphic card instead of my second one (NVIDIA GTX 1060). 
Even thought I selected to use the NVIDIA one in NVIDIA control Panel. It still used the intergrated one!
So I disabled the intergrated one and now the game is perfect again!!
It is using my NVIDIA GTX 1060 and it is so good!

I really hope this will help you too. And I hope I explained it a bit ok.

(ps: english not my native language so please don't mind the mistakes)
Greeting and have a great day Dipster78

**Comment by VolkertJansz** [comment] 2020-02-19 11:01
Also a great suggestion. I will add it to the list of possibilities. Although I don't think my integrated GPU would be able to run it the way it does (I have 2x MSAA on, and everything quite high). But I'll be sure to check it out when the wait for the Valve Index is taking too long. For now I'm using Vorpx to play some golden oldies in VR. Nothing beats this mod though ;P

**Comment by VolkertJansz** [comment] 2020-02-19 11:15
Just did a little check, turned off my integrated graphics in the BIOS, stutter still there. I haven't tried the suggestions from d0x360 yet though. That could still do the trick. Thanks all.

**Comment by d0x360** [comment] 2020-02-19 13:24
I gave the game a shot and it worked amazingly well at higher than suggested settings (shadows, draw distance etc) with 2xSSAA, 2xMSAA and TXAA and I also had a couple mods installed that improved visuals.

I didn't get any frame rate or frame pacing issues.

If you try the stuff I listed and it doesn't help I would also suggest a clean driver install using DDU from guru3d and if all else fails... Give Windows a fresh install via the reset option.  It usually needs it after a couple years anyways.

**Comment by Dipster78** [comment] 2020-02-20 10:44
To bad it didn't work. My CPU can't run it either in a good way but GTA V keeps using the intergrated one.
For me disabeling the intergrated graphic card is the only option to play the game in VR.
I do have to turn it back on after playing because weirdly enough some programs work better when I enable it....so weird.

I hope you find a solution. Good luck! Will be keeping an eye on this topic.
Have a great day

**Comment by VolkertJansz** [comment] 2020-02-20 16:49
Unfortunately the Oculus Tray Tool suggestions also didn't do the trick for me. So the last resort I see is a Windows re-install.

**Comment by LukeRoss00** [comment] 2020-02-20 18:09
You never wrote whether you had any success with the options that I suggested [here](https://github.com/LukeRoss00/gta5-real-mod/issues/109#issuecomment-586285887)...

**Comment by d0x360** [comment] 2020-02-20 18:17
By any chance is your PC set to power savings mode or anything like that?  In the windows cp make sure it's set to high performance.  Also try opening the Xbox/gaming section in the cp and if game mode is on try shutting it off and if it's off try turning it on.  Also shut off the open gamebar with guide button and lastly in steam try shutting the steam overlay off in gta5' properties.

**Comment by VolkertJansz** [comment] 2020-02-21 12:09
@LukeRoss00 Hi, yeah, sorry. I did try the numpad+ option to no avail. Just forgot to mention it being oversnowed by other potential fixes. I didn't try to investigate the issue further using LatencyMon. At the moment I'm re-playing Dishonored using Vorpx and am leaving GTA for when I get an Index (not only because of the stutter, which might just be resolved or less noticeable on the Index higher refresh rates, but also because I want to experience the glory of your mod for many many hours, in the best possible fidelity). I know that it might be usefull for other if I try to find the culpritt using LatencyMon. So if anyone else pops up here with a similar issue I'm very willing to pick up the troubleshooting again. For now, it's iRacing and Dishonored for me. Thanks a lot though! 

@d0x360 Those were the first things that I've tried, but thanks for the suggestions!

**Comment by LukeRoss00** [comment] 2020-02-21 12:26
Okay, I'm closing the issue then. Feel free to reopen in the future if you have new information

**Closed by LukeRoss00** 2020-02-21 12:26 UTC

**Comment by VolkertJansz** [comment] 2020-03-28 17:19
Getting a Valve index got rid of the weird stutter. Don't know if that info is very helpful for people experiencing the issue. But at least we can safely say that it had something to do with oculus. After checking it with the Index I went back to the Rift S and it came back. Still loving the mod, cheers

**Comment by d0x360** [comment] 2020-03-28 17:21
It doesn't say it had to do with the Oculus at all, it says there was an
issue with your install of the Oculus software and services.

It works perfectly fine for tons of people on Oculus.  If there was an
oculus specific issue it would effect all of us.

**Comment by VolkertJansz** [comment] 2020-03-28 17:30
Yes, you are right. I'm sorry if I offended any Oculus users. But my issue was solved when not using Oculus so I can safely say "it had something to do with Oculus" :p

**Comment by d0x360** [comment] 2020-03-28 17:49
No offense taken, I'm just saying the issue was your Oculus install.  It
working fine for you on vive proves that fact.

It also proves the issue was probably easily fixable.
